version: "3"
services:
  bank-service:
    image: jackkeck3/bank-service:init
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - webnet
networks:
  webnet:
